(() => {
  'use strict';
  const config = window.APP_CONFIG || {}; const $ = (s) => document.querySelector(s);
  const el = { signin: $('#signin'), signinForm: $('#signin-form'), email: $('#email'), signinStatus: $('#signin-status'), console: $('#console'), signout: $('#signout'), masterEmail: $('#master-email'), pairingCode: $('#pairing-code'), assignRoom: $('#assign-room'), approve: $('#approve'), pairingStatus: $('#pairing-status'), scan: $('#scan'), reader: $('#qr-reader'), source: $('#source-room'), destination: $('#destination'), priority: $('#priority'), message: $('#message'), form: $('#notice-form'), list: $('#notice-list'), toast: $('#toast') };
  const state = { client: null, rooms: [], notices: [], channel: null, scanner: null };
  const text = (target, value, kind = '') => { target.textContent = value; target.className = kind; };
  const toast = (message) => { el.toast.textContent = message; el.toast.classList.remove('hidden'); clearTimeout(toast.timer); toast.timer = setTimeout(() => el.toast.classList.add('hidden'), 4200); };
  const roomName = (id) => state.rooms.find((room) => room.id === id)?.name || 'Sala no disponible';
  const cleanCode = (value) => String(value || '').toUpperCase().replace(/[^A-Z0-9]/g, '');
  function populateRooms() { [el.assignRoom, el.source].forEach((select) => { select.replaceChildren(); state.rooms.forEach((room) => select.add(new Option(room.name, room.code))); }); el.destination.replaceChildren(); el.destination.add(new Option('⚠️ Todas las salas', 'ALL')); state.rooms.forEach((room) => el.destination.add(new Option(room.name, room.code))); }
  function renderNotices() { el.list.replaceChildren(); if (!state.notices.length) { const empty = document.createElement('div'); empty.className = 'empty'; empty.textContent = 'No hay avisos disponibles.'; el.list.append(empty); return; } for (const notice of state.notices) { const card = document.createElement('article'); card.className = `notice ${notice.priority}`; const meta = document.createElement('div'); meta.className = 'meta'; meta.textContent = `${notice.priority === 'immediate' ? '🔴 Inmediato' : notice.priority === 'urgent' ? '🟠 Urgente' : '🔵 No urgente'} · Desde: ${roomName(notice.source_room_id)} · ${notice.destination_room_id ? `Para: ${roomName(notice.destination_room_id)}` : 'Para: Todas las salas'} · ${new Intl.DateTimeFormat('es-CL', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(notice.created_at))}`; const body = document.createElement('p'); body.textContent = notice.body; card.append(meta, body); el.list.append(card); } }
  async function loadRooms() { const { data, error } = await state.client.from('rooms').select('id,code,name').eq('active', true).order('name'); if (error) throw error; state.rooms = data || []; populateRooms(); }
  async function loadNotices() { const { data, error } = await state.client.from('notices').select('id,source_room_id,destination_room_id,body,priority,status,created_at').order('created_at', { ascending: false }).limit(100); if (error) throw error; state.notices = data || []; renderNotices(); }
  function subscribe() { state.channel?.unsubscribe(); state.channel = state.client.channel('master', { config: { private: true } }).on('postgres_changes', { event: '*', schema: 'public', table: 'notices' }, () => loadNotices().catch((error) => console.error(error))).subscribe(); }
  async function approve() { const code = cleanCode(el.pairingCode.value); if (!code) return text(el.pairingStatus, 'Escanea un QR antes de asignar.', 'error'); el.approve.disabled = true; text(el.pairingStatus, 'Asignando terminal…'); try { const room = state.rooms.find((item) => item.code === el.assignRoom.value); const { error } = await state.client.rpc('approve_terminal_pairing', { p_code: code, p_room_code: el.assignRoom.value, p_label: `${room?.name || 'Sala'} · QR` }); if (error) throw error; el.pairingCode.value = ''; text(el.pairingStatus, 'Terminal asignado correctamente.', 'ok'); toast('Terminal vinculado a la sala.'); } catch (error) { text(el.pairingStatus, error.message || 'No fue posible asignar el terminal.', 'error'); } finally { el.approve.disabled = false; } }
  async function send(event) { event.preventDefault(); const body = el.message.value.trim(); if (!body) return; const button = el.form.querySelector('button'); button.disabled = true; try { const { error } = await state.client.rpc('create_master_notice', { p_source_room_code: el.source.value, p_destination_code: el.destination.value, p_body: body, p_priority: el.priority.value }); if (error) throw error; el.message.value = ''; await loadNotices(); toast('Aviso enviado como la sala seleccionada.'); } catch (error) { toast(error.message || 'No fue posible enviar el aviso.'); } finally { button.disabled = false; } }
  async function stopScanner() { if (state.scanner) { try { await state.scanner.stop(); } catch { /* La cámara ya puede estar detenida. */ } state.scanner.clear(); state.scanner = null; } el.reader.classList.add('hidden'); el.scan.textContent = '📷 Escanear QR'; }
  async function scan() { if (state.scanner) return stopScanner(); if (!window.Html5Qrcode) return text(el.pairingStatus, 'No se pudo cargar el lector QR.', 'error'); el.reader.classList.remove('hidden'); state.scanner = new Html5Qrcode('qr-reader'); el.scan.textContent = 'Detener cámara'; try { await state.scanner.start({ facingMode: 'environment' }, { fps: 10, qrbox: { width: 220, height: 220 } }, async (decoded) => { el.pairingCode.value = cleanCode(decoded); await stopScanner(); text(el.pairingStatus, 'QR leído. Elige la sala y confirma.'); }); } catch (error) { await stopScanner(); text(el.pairingStatus, 'No fue posible abrir la cámara. Puedes pegar el contenido del QR.', 'error'); } }
  async function requestLink(event) { event.preventDefault(); text(el.signinStatus, 'Enviando enlace…'); const redirect = new URL('master.html', location.href).href; const { error } = await state.client.auth.signInWithOtp({ email: el.email.value.trim().toLowerCase(), options: { emailRedirectTo: redirect } }); text(el.signinStatus, error ? error.message : 'Revisa tu correo y abre el enlace en este navegador.', error ? 'error' : 'ok'); }
  async function enterConsole() { const { data, error } = await state.client.rpc('my_master_context'); if (error) throw error; el.masterEmail.textContent = `Sesión autorizada: ${data?.[0]?.email || ''}`; await loadRooms(); await loadNotices(); subscribe(); el.signin.classList.add('hidden'); el.console.classList.remove('hidden'); el.signout.classList.remove('hidden'); }
  async function start() { if (!config.supabaseUrl || !config.supabasePublishableKey || !window.supabase) return text(el.signinStatus, 'Falta la configuración de Supabase.', 'error'); state.client = window.supabase.createClient(config.supabaseUrl, config.supabasePublishableKey, { auth: { persistSession: true, autoRefreshToken: true } }); el.signinForm.addEventListener('submit', requestLink); el.approve.addEventListener('click', approve); el.scan.addEventListener('click', scan); el.form.addEventListener('submit', send); el.signout.addEventListener('click', async () => { await stopScanner(); await state.client.auth.signOut(); location.reload(); }); const { data: { session } } = await state.client.auth.getSession(); if (!session) return; try { await enterConsole(); } catch (error) { text(el.signinStatus, error.message || 'Esta cuenta no está autorizada.', 'error'); } }
  addEventListener('DOMContentLoaded', start);
})();
